// Vietnamese study notes for openings (idea, plans for both sides, a tip) and Vietnamese opening names.
// Ordered: the first pattern that matches the full lichess name wins, so specific lines come first.
const GUIDES = [
  /* ---- specific variations (checked first) ---- */
  { re: /Sveshnikov|Pelikan/, vn: 'Sicilia Sveshnikov',
    idea: 'Đen đi ...Nc6 và ...e5 sớm, chấp nhận ô d5 yếu và tốt d6 lạc hậu để đổi lấy quân hoạt động và cặp Tượng.',
    white: ['Chiếm ô d5 bằng Mã (Nd5)', 'Chơi c3, a4 để khóa cánh Hậu'],
    black: ['Phá bằng ...f5 đúng lúc', 'Đẩy ...b5 giành không gian cánh Hậu'],
    tip: 'Sắc bén, được Carlsen và Kramnik sử dụng ở đỉnh cao.' },
  { re: /Sicilian Defense: Taimanov/, vn: 'Sicilia Taimanov',
    idea: 'Đen đi ...e6, ...Nc6 và thường ...Qc7, ...a6: một hệ thống linh hoạt, chưa vội quyết định vị trí các quân.',
    white: ['Be3, Qd2 hoặc Bd3 và nhập thành', 'Tận dụng không gian ở trung tâm'],
    black: ['...Nf6, ...Bb4 hoặc ...Be7', 'Phản công cột c và ô e5'],
    tip: 'Ít lý thuyết bắt buộc hơn Najdorf.' },
  { re: /Sicilian Defense: Kan/, vn: 'Sicilia Kan (Paulsen)',
    idea: 'Đen đi ...e6 và ...a6 sớm, giữ tốt d7 linh hoạt và chuẩn bị ...b5, ...Bb7.',
    white: ['Bd3, O-O, c4 để khóa cánh Hậu', 'Chơi Nc3 và Qe2 chuẩn bị e5'],
    black: ['...Qc7, ...Nf6, ...b5', 'Giữ thế cờ đàn hồi, chờ phản công'],
    tip: 'Hợp với người thích cờ linh hoạt.' },
  { re: /Sicilian Defense: Scheveningen/, vn: 'Sicilia Scheveningen',
    idea: 'Đen dựng "trung tâm nhỏ" bằng tốt e6 và d6, kiểm soát d5 và e5 rồi phản công.',
    white: ['Tấn công Keres g4-g5 hoặc f4, Qf3', 'Nhập thành xa rồi đẩy tốt cánh Vua'],
    black: ['...a6, ...Qc7, ...b5', 'Phá trung tâm bằng ...d5 hoặc ...e5'],
    tip: 'Cấu trúc e6-d6 rất vững nếu Đen kịp phát triển.' },
  { re: /Accelerated Dragon|Hyperaccelerated/, vn: 'Sicilia Rồng tăng tốc',
    idea: 'Đen đưa Tượng lên g7 trước khi đi ...d6, tránh được tấn công Yugoslav và có thể đi ...d5 một nước.',
    white: ['Maróczy: c4 kẹp ô d5', 'Phát triển tự nhiên, giữ không gian'],
    black: ['...d5 một nước khi được', 'Chơi ...Nc6, ...Nf6, ...O-O'],
    tip: 'Nếu Trắng đi c4 (Maróczy), ván cờ thành đấu vị trí.' },
  { re: /Sicilian Defense: (Nyezhmetdinov-)?Rossolimo|Sicilian Defense: Bowdler|Sicilian Defense: Moscow/, vn: 'Sicilia với Bb5',
    idea: 'Trắng đi Bb5 sớm (Rossolimo hoặc Moscow) để tránh Sicilia mở, thường đổi Tượng lấy Mã làm hỏng cấu trúc tốt Đen.',
    white: ['O-O, Re1, c3 và d4', 'Đổi Bxc6 khi Đen có tốt chồng'],
    black: ['...g6, ...Bg7 hoặc ...e6', 'Giữ cặp Tượng, chơi chắc'],
    tip: 'Lựa chọn yêu thích để tránh lý thuyết Najdorf.' },
  { re: /Closed Sicilian|Sicilian Defense: Closed/, vn: 'Sicilia đóng',
    idea: 'Trắng đi Nc3, g3, Bg2, d3 và f4: không mở trung tâm, dồn lực tấn công cánh Vua.',
    white: ['f4, Nf3, O-O rồi f5', 'Be3, Qd2, Bh6 đổi Tượng g7'],
    black: ['Phản công cánh Hậu: ...Rb8, ...b5', 'Kiểm soát ô d4 bằng Mã'],
    tip: 'Kế hoạch rõ ràng, hợp người mới.' },
  { re: /Grand Prix/, vn: 'Tấn công Grand Prix',
    idea: 'Trắng đi Nc3 và f4 sớm, rồi Bc4 hoặc Bb5, hướng tới tấn công nhanh cánh Vua.',
    white: ['f4-f5, Qe1-h4', 'Đưa Tượng c4 nhắm e6'],
    black: ['...d5 phá trung tâm sớm', 'Không nhập thành vội về phía bị tấn công'],
    tip: 'Rất phổ biến ở cờ nhanh.' },
  { re: /French Defense: Winawer/, vn: 'Pháp, biến Winawer',
    idea: '3...Bb4 ghim Mã c3. Sau e5 và a3, Đen thường đổi Bxc3 để làm hỏng cấu trúc tốt Trắng.',
    white: ['Qg4 tấn công g7, dùng cặp Tượng', 'Tấn công cánh Vua nơi Tượng đen vắng mặt'],
    black: ['...c5, ...Ne7, ...Qa5 đè cánh Hậu', 'Nhắm vào tốt chồng c3-c2'],
    tip: 'Một trong những biến sắc bén nhất của Phòng thủ Pháp.' },
  { re: /French Defense: Tarrasch/, vn: 'Pháp, biến Tarrasch (3.Nd2)',
    idea: '3.Nd2 tránh ghim ...Bb4. Ván cờ thường dẫn tới cấu trúc tốt d cô lập.',
    white: ['Ngf3, Bb5, O-O', 'Phong tỏa tốt cô lập ở d4'],
    black: ['...c5 sớm, chấp nhận tốt d5 cô lập', 'Quân hoạt động bù lại điểm yếu'],
    tip: 'Hợp với người thích cờ vị trí.' },
  { re: /French Defense: Exchange/, vn: 'Pháp, biến Đổi quân',
    idea: 'Trắng ăn exd5, cấu trúc tốt đối xứng và ván cờ yên tĩnh. Tượng c8 của Đen được giải phóng.',
    white: ['Phát triển nhanh, Bd3, Nf3', 'Chiếm cột e mở'],
    black: ['Phát triển đối xứng, nhập thành', 'Chơi ...Bg4 hoặc ...Bf5'],
    tip: 'Ít tham vọng, dễ hòa nếu không có kế hoạch.' },
  { re: /Caro-Kann Defense: Panov/, vn: 'Caro-Kann, tấn công Panov',
    idea: 'Trắng đi exd5 rồi c4: ván cờ có tốt d cô lập giống Gambit Hậu, quân hoạt động cho Trắng.',
    white: ['Nc3, Nf3, phát triển nhanh', 'Dùng tốt d4 để chiếm e5'],
    black: ['Phong tỏa ô d5, đổi quân', 'Đưa tốt cô lập vào tàn cuộc'],
    tip: 'Cách chơi tích cực trước Caro-Kann.' },
  { re: /Caro-Kann Defense: Classical/, vn: 'Caro-Kann, biến Cổ điển',
    idea: 'Sau 3.Nc3 dxe4 4.Nxe4 Bf5, Tượng Đen ra ngoài trước ...e6. Trắng đuổi Tượng bằng Ng3 và h4-h5.',
    white: ['h4-h5 giành không gian, nhập thành xa', 'Đổi Tượng trắng rồi dùng không gian'],
    black: ['...Nd7, ...Ngf6, ...e6, ...Qc7', 'Cấu trúc vững, ít điểm yếu'],
    tip: 'Biến chính lâu đời và chắc chắn nhất của Caro-Kann.' },
  { re: /Caro-Kann Defense: Exchange/, vn: 'Caro-Kann, biến Đổi quân',
    idea: 'Trắng ăn exd5 rồi dựng c3, Bd3: cấu trúc Carlsbad đảo màu, kế hoạch tấn công cánh Vua.',
    white: ['Bd3, c3, Qc2 nhắm h7', 'Bf4 kiểm soát ô b8-h2'],
    black: ['...Nc6, ...Bg4, tấn công thiểu số ...b5-b4', 'Đổi Tượng trắng của Trắng'],
    tip: 'Đơn giản nhưng có độc.' },
  { re: /Ruy Lopez: Marshall/, vn: 'Tấn công Marshall',
    idea: 'Đen thí tốt e5 bằng ...d5, đổi lại có tấn công lâu dài vào Vua Trắng.',
    white: ['Nhận tốt, phòng thủ chính xác bằng d4, Re1', 'Đổi quân để đi vào tàn cuộc hơn tốt'],
    black: ['...Bd6, ...Qh4, ...Bg4 dồn lên cánh Vua', 'Không vội lấy lại tốt'],
    tip: 'Nhiều kiện tướng tránh 8.c3 chỉ vì gambit này.' },
  { re: /Ruy Lopez: Exchange/, vn: 'Tây Ban Nha, biến Đổi quân',
    idea: 'Trắng đổi Bxc6: Đen có cặp Tượng nhưng tốt chồng c. Trắng nhắm tới tàn cuộc với đa số tốt cánh Vua.',
    white: ['d4 mở trung tâm, đổi Hậu', 'Dùng đa số tốt 4 đấu 3 cánh Vua'],
    black: ['Dùng cặp Tượng, giữ nhiều quân', 'Chơi ...f6 hoặc ...Bg4 bảo vệ e5'],
    tip: 'Fischer rất thích biến này.' },
  { re: /Traxler|Wilkes-Barre/, vn: 'Phản đòn Traxler',
    idea: 'Sau 4.Ng5, Đen bỏ f7 và đi 4...Bc5!? phản công ngay vào f2. Cực kỳ sắc bén.',
    white: ['5.Bxf7+ hoặc 5.Nxf7, tính thật chính xác', 'Không để Vua bị kéo ra giữa bàn'],
    black: ['...Bxf2+ và ...Nxe4 tấn công Vua', 'Chấp nhận thí quân để lấy thế chủ động'],
    tip: 'Rất nguy hiểm ở cờ nhanh nếu đối thủ không biết.' },
  { re: /Scotch Gambit/, vn: 'Gambit Scotland',
    idea: 'Trắng đi d4 rồi Bc4 thay vì ăn lại tốt ngay, phát triển nhanh để tấn công.',
    white: ['Bc4, O-O, e5', 'Nhắm vào f7'],
    black: ['...Nf6 hoặc ...Bc5', 'Trả tốt đúng lúc để phát triển'],
    tip: 'Hay chuyển thành Hai Mã hoặc Giuoco Piano.' },
  { re: /Halloween/, vn: 'Gambit Halloween',
    idea: 'Trắng thí Mã bằng Nxe5?! để đẩy tốt trung tâm đuổi quân Đen. Mạo hiểm, không chính xác nếu Đen phòng thủ đúng.',
    white: ['d4, e5 đuổi Mã', 'Tấn công nhanh trước khi Đen gỡ rối'],
    black: ['Giữ quân thừa, trả lại khi cần', 'Phát triển và nhập thành'],
    tip: 'Đen chơi bình tĩnh là hơn quân.' },
  { re: /Cochrane/, vn: 'Gambit Cochrane',
    idea: 'Trong Petrov, Trắng thí Mã ở f7 (Nxf7) để kéo Vua Đen ra và tấn công.',
    white: ['d4, Nc3, tấn công Vua ở giữa', 'Dùng tốt trung tâm'],
    black: ['Vua lùi về g8, phát triển quân', 'Hơn quân thì đổi bớt'],
    tip: 'Hiếm gặp nhưng khó chơi với Đen nếu chưa biết.' },
  { re: /Queen's Gambit Declined: Exchange/, vn: 'Gambit Hậu từ chối, biến Đổi quân',
    idea: 'Trắng ăn cxd5 tạo cấu trúc Carlsbad. Kế hoạch nổi tiếng: tấn công thiểu số b4-b5 cánh Hậu.',
    white: ['Bd3, Qc2, Nge2 hoặc Nf3', 'b4-b5 tạo điểm yếu ở c6'],
    black: ['...Ne4, ...f5 tấn công cánh Vua', 'Hoặc phòng thủ chắc cánh Hậu'],
    tip: 'Bài học kinh điển về kế hoạch trung cuộc.' },
  { re: /Albin Countergambit/, vn: 'Phản gambit Albin',
    idea: '2...e5!? phản công. Tốt d4 của Đen cản trở phát triển của Trắng.',
    white: ['g3, Bg2, Nbd2 rồi lấy tốt d4', 'Giữ tốt e5 thừa'],
    black: ['...Nc6, ...Be6, ...Qd7, nhập thành xa', 'Tận dụng tốt d4 kìm hãm'],
    tip: 'Có bẫy Lasker nổi tiếng: tốt Đen phong Mã có chiếu.' },
  { re: /Queen's Gambit Declined: Chigorin/, vn: 'Phòng thủ Chigorin',
    idea: '2...Nc6 phát triển Mã trước tốt c, gây áp lực lên d4 bằng quân.',
    white: ['Nf3, Nc3, giữ trung tâm', 'Chiếm cặp Tượng khi được'],
    black: ['...Bg4 đè d4', 'Chơi quân, không ngại mất cấu trúc'],
    tip: 'Khác thường và bất ngờ.' },
  { re: /Semi-Slav Defense: Meran/, vn: 'Bán Slav, biến Meran',
    idea: 'Đen ăn ...dxc4 rồi ...b5, ...Bb7, chuẩn bị ...c5 hoặc ...b4 phản công cánh Hậu.',
    white: ['Bd3, e4-e5 đuổi Mã f6', 'Tấn công trung tâm nhanh'],
    black: ['...a6, ...c5, ...Bb7', 'Mở cánh Hậu'],
    tip: 'Sắc bén và giàu lý thuyết.' },
  { re: /King's Indian Defense: Sämisch/, vn: 'Ấn Độ Vua, biến Sämisch',
    idea: 'Trắng đi f3 củng cố e4, chuẩn bị Be3, Qd2 và có thể nhập thành xa rồi tấn công bằng g4, h4.',
    white: ['Be3, Qd2, O-O-O rồi h4-h5', 'Giữ trung tâm cứng'],
    black: ['...e5 hoặc ...c5 phá trung tâm', '...Nc6, ...a6, ...b5 phản công'],
    tip: 'Hai bên tấn công hai cánh, ai nhanh hơn thắng.' },
  { re: /King's Indian Defense: Four Pawns/, vn: 'Ấn Độ Vua, biến Bốn Tốt',
    idea: 'Trắng dựng bốn tốt c4, d4, e4, f4: trung tâm khổng lồ nhưng phát triển chậm.',
    white: ['Nf3, Be2, O-O rồi e5', 'Giữ trung tâm liền mạch'],
    black: ['...c5 và ...e6 phá ngay', 'Tấn công trung tâm trước khi Trắng kịp phát triển'],
    tip: 'Trung tâm lớn là mục tiêu nếu thiếu quân bảo vệ.' },
  { re: /King's Indian Defense: Fianchetto/, vn: 'Ấn Độ Vua, biến Fianchetto',
    idea: 'Trắng đưa Tượng lên g2, chơi vị trí, giữ Vua an toàn.',
    white: ['Nf3, g3, Bg2, O-O, Nc3', 'Áp lực lâu dài trên đường chéo dài'],
    black: ['...Nc6 và ...a6 (biến Panno) hoặc ...e5', 'Phản công cánh Hậu'],
    tip: 'Cách chơi an toàn trước KID.' },
  { re: /Nimzo-Indian Defense: Rubinstein|Nimzo-Indian Defense: Normal/, vn: 'Nimzo-Ấn, biến Rubinstein (4.e3)',
    idea: 'Trắng đi e3, phát triển chắc chắn: Bd3, Nf3, O-O. Chấp nhận tốt chồng để có trung tâm và cặp Tượng.',
    white: ['Bd3, Nf3 hoặc Ne2, O-O', 'Đẩy e4 khi đủ quân'],
    black: ['...c5, ...d5, ...b6 tùy hệ thống', 'Đổi Bxc3 khi tốt chồng thành điểm yếu'],
    tip: 'Biến phổ biến nhất trước Nimzo-Ấn.' },
  { re: /Nimzo-Indian Defense: Classical/, vn: 'Nimzo-Ấn, biến Cổ điển (4.Qc2)',
    idea: 'Trắng đi Qc2 để nếu Đen đổi Bxc3 thì ăn lại bằng Hậu, giữ cấu trúc tốt nguyên vẹn.',
    white: ['a3 lấy cặp Tượng', 'e4 sau khi phát triển'],
    black: ['...O-O, ...d5 hoặc ...c5', 'Phát triển nhanh vì Hậu Trắng ra sớm'],
    tip: 'Lựa chọn hiện đại, vị trí.' },
  { re: /Grünfeld Defense: Exchange/, vn: 'Grünfeld, biến Đổi quân',
    idea: 'Trắng ăn cxd5 và e4 đuổi Mã, dựng trung tâm c3-d4-e4 lớn. Đen dồn áp lực lên d4.',
    white: ['Bc4, Ne2, O-O giữ trung tâm', 'Đẩy d5 khi thuận lợi'],
    black: ['...c5, ...Nc6, ...Qa5', 'Tượng g7 là quân mạnh nhất'],
    tip: 'Biến chính quan trọng nhất của Grünfeld.' },
  { re: /^Slav Defense: Exchange/, vn: 'Slav, biến Đổi quân',
    idea: 'Trắng ăn cxd5 sớm, cấu trúc đối xứng. Ván cờ yên tĩnh.',
    white: ['Bf4, Nc3, Rc1 dùng cột c mở', 'Chơi vị trí'],
    black: ['Phát triển đối xứng', 'Tranh chấp cột c'],
    tip: 'Hay dẫn tới hòa ở trình cao.' },
  { re: /Dutch Defense: (Semi-)?Leningrad/, vn: 'Hà Lan, biến Leningrad',
    idea: 'Đen kết hợp ...f5 với ...g6, ...Bg7: giống Ấn Độ Vua, tấn công cánh Vua bằng ...e5.',
    white: ['g3, Bg2, c4, Nc3, d5', 'Chiếm không gian'],
    black: ['...d6, ...Qe8, ...e5', 'Tượng g7 kiểm soát đường chéo dài'],
    tip: 'Sắc bén hơn Stonewall.' },
  { re: /Dutch Defense: Stonewall/, vn: 'Hà Lan, biến Stonewall',
    idea: 'Đen dựng tốt c6, d5, e6, f5 như bức tường, kiểm soát e4 rồi tấn công cánh Vua.',
    white: ['b3 và Ba3 đổi Tượng tốt của Đen', 'Chiếm ô e5 bằng Mã'],
    black: ['Mã lên e4, ...Qe7, ...Rf6-h6', 'Đưa Tượng c8 ra qua d7-e8-h5'],
    tip: 'Ô e5 là điểm yếu lâu dài của Đen.' },
  { re: /English Opening: Symmetrical/, vn: 'Anh, biến Đối xứng',
    idea: 'Đen đáp 1...c5: hai bên đi đối xứng, ván cờ vị trí.',
    white: ['Nc3, g3, Bg2, Nf3 rồi d4', 'Tranh thủ lượt đi trước'],
    black: ['Giữ đối xứng hoặc phá bằng ...d5', 'Phát triển nhanh'],
    tip: 'Tránh đối xứng quá lâu, Trắng luôn đi trước một nhịp.' },
  { re: /English Opening: King's English|Reversed Sicilian/, vn: 'Anh, Sicilia đảo màu',
    idea: 'Đen đáp 1...e5: như Phòng thủ Sicilia nhưng Trắng hơn một nước.',
    white: ['Nc3, g3, Bg2, Nf3', 'd3 và b4 mở cánh Hậu'],
    black: ['...Nc6, ...Nf6, ...d5 hoặc ...Bb4', 'Chiếm trung tâm bằng tốt'],
    tip: 'Nhiều ý tưởng từ Sicilia áp dụng được ở đây.' },
  { re: /Scandinavian Defense: (Modern|Marshall|Icelandic|Portuguese|Richter)/, vn: 'Scandinavia, biến Hiện đại (2...Nf6)',
    idea: 'Đen ăn lại tốt d5 bằng Mã thay vì Hậu, tránh mất nhịp. Có vài gambit sắc bén (Iceland, Bồ Đào Nha).',
    white: ['d4, c4 đuổi Mã', 'Giữ tốt thừa nếu Đen thí'],
    black: ['...Nxd5, ...g6, ...Bg7', 'Tấn công trung tâm Trắng'],
    tip: 'Tránh việc Hậu bị đuổi như biến 2...Qxd5.' },
  { re: /Alekhine Defense: Four Pawns/, vn: 'Alekhine, tấn công Bốn Tốt',
    idea: 'Trắng đuổi Mã bằng c4, d4, e5, f4: trung tâm khổng lồ nhưng dễ trở thành mục tiêu.',
    white: ['Giữ trung tâm liền mạch, phát triển nhanh', 'Đẩy d5 hoặc f5 khi thuận lợi'],
    black: ['...Bf5, ...Nc6, ...e6 tấn công trung tâm', 'Phá bằng ...c5 hoặc ...f6'],
    tip: 'Thử thách lớn nhất đối với Alekhine.' },
  { re: /Pirc Defense: Austrian/, vn: 'Pirc, tấn công Áo',
    idea: 'Trắng đi f4, dựng ba tốt trung tâm và nhắm tới e5 hoặc f5 tấn công.',
    white: ['Nf3, Bd3, O-O rồi e5', 'Qe1-h4 tấn công cánh Vua'],
    black: ['...c5 hoặc ...Na6-c7 phản công', 'Không để trung tâm tràn qua'],
    tip: 'Cách chơi hung hăng nhất trước Pirc.' },
  { re: /Colle System|Colle-Zukertort/, vn: 'Hệ thống Colle',
    idea: 'Trắng đi d4, e3, Bd3, Nbd2, O-O rồi e4: hệ thống đơn giản nhắm tới tấn công cánh Vua.',
    white: ['e4 mở trung tâm', 'Tượng d3 nhắm h7'],
    black: ['...c5, ...Nc6, ...Bd6', 'Chuẩn bị cho e4 bằng ...Qc7'],
    tip: 'Dễ học, kế hoạch lặp lại.' },
  { re: /Torre Attack/, vn: 'Tấn công Torre',
    idea: 'Trắng đi d4, Nf3 và Bg5 ghim Mã f6, rồi e3, Nbd2, c3.',
    white: ['e4 khi đủ quân', 'Bxf6 làm hỏng cấu trúc Đen khi có lợi'],
    black: ['...c5 và ...Qb6 nhắm b2', '...h6 đuổi Tượng'],
    tip: 'Hệ thống chắc chắn, ít lý thuyết.' },
  { re: /Trompowsky/, vn: 'Tấn công Trompowsky',
    idea: '2.Bg5 ngay sau 1...Nf6, đe dọa đổi Tượng lấy Mã làm hỏng cấu trúc tốt Đen.',
    white: ['Bxf6 hoặc lui Bf4, h4', 'Chơi e3, c3 chắc chắn'],
    black: ['...Ne4 hoặc ...e6, ...c5', 'Nhắm b2 bằng ...Qb6'],
    tip: 'Tránh được lý thuyết Ấn Độ dài dòng.' },
  { re: /Jobava|Rapport/, vn: 'Hệ thống Jobava London',
    idea: 'Trắng kết hợp Nc3 với Bf4: giống London nhưng tích cực hơn, nhắm Nb5 và c7.',
    white: ['Nb5 đe dọa c7', 'e3, Bd3, Qf3 hoặc h4'],
    black: ['...a6 ngăn Nb5', '...c5 và ...Nc6 phản công'],
    tip: 'Hệ thống mới, gây bất ngờ tốt.' },
  { re: /Stonewall Attack/, vn: 'Tấn công Stonewall',
    idea: 'Trắng dựng tốt d4, e3, f4, c3 và Bd3, Ne5: tấn công cánh Vua theo sơ đồ cố định.',
    white: ['Ne5, Qf3, g4-g5', 'Tượng d3 nhắm h7'],
    black: ['Đổi Mã e5, phản công bằng ...c5', 'Ô e4 là điểm mạnh cho Mã Đen'],
    tip: 'Hiệu quả ở trình phổ thông.' },
  { re: /Owen Defense/, vn: 'Phòng thủ Owen',
    idea: '1...b6 đưa Tượng lên b7 nhắm e4. Ít gặp.',
    white: ['Chiếm trung tâm, Bd3 bảo vệ e4', 'Phát triển nhanh'],
    black: ['...Bb7, ...e6, ...c5', 'Gây áp lực e4'],
    tip: 'Trắng chơi tự nhiên là đủ tốt.' },
  { re: /Polish Opening/, vn: 'Khai cuộc Ba Lan (1.b4)',
    idea: '1.b4 chiếm không gian cánh Hậu, đưa Tượng lên b2 nhắm đường chéo dài.',
    white: ['Bb2, a3, e3, Nf3', 'Tấn công ô e5'],
    black: ['...e5 hoặc ...d5 chiếm trung tâm', 'Đánh vào tốt b4'],
    tip: 'Khai cuộc lạ, hợp để gây bất ngờ.' },
  { re: /Grob Opening/, vn: 'Khai cuộc Grob (1.g4)',
    idea: '1.g4 đưa Tượng lên g2 nhắm b7, nhưng làm yếu cánh Vua.',
    white: ['Bg2, c4 gây áp lực cánh Hậu', 'Cẩn thận ô f3, h3'],
    black: ['...d5 và ...Bxg4 hoặc chiếm trung tâm', 'Tấn công Vua Trắng đã yếu'],
    tip: 'Mạo hiểm, không được khuyến khích.' },
  { re: /Nimzo-Larsen Attack/, vn: 'Tấn công Nimzo-Larsen (1.b3)',
    idea: '1.b3 và Bb2 kiểm soát trung tâm từ xa, linh hoạt.',
    white: ['Bb2, e3, Nf3, c4', 'Chơi vị trí'],
    black: ['...e5 hoặc ...d5 chiếm trung tâm', 'Cẩn thận đường chéo dài'],
    tip: 'Larsen dùng thành công ở đẳng cấp cao.' },
  /* ---- families and specific lines from before ---- */
  { re: /Fried Liver/, vn: 'Tấn công Gan Rán (Fried Liver)',
    idea: 'Sau 4.Ng5 d5 5.exd5 Nxd5?!, Trắng thí Mã ở f7 để kéo Vua Đen ra giữa bàn rồi dồn quân tấn công.',
    white: ['Nxf7 rồi Qf3+ đưa Hậu vào cuộc, ghim Mã d5', 'Đưa thêm quân (Nc3, d4, O-O) trước khi Vua Đen kịp chạy'],
    black: ['Tránh 5...Nxd5; đi 5...Na5 là cách chuẩn', 'Nếu đã vào biến thí Mã, đưa Vua về e6 và phòng thủ bằng ...Ncb4, ...c6'],
    tip: 'Người mới cầm Đen thường thua nhanh ở đây. Nhớ: 5...Na5!, không ăn lại bằng Mã.' },
  { re: /Two Knights Defense/, vn: 'Phòng thủ Hai Mã',
    idea: 'Đen đi 3...Nf6 phản công tốt e4 thay vì 3...Bc5. Ván cờ có thể rất sắc bén nếu Trắng đánh 4.Ng5.',
    white: ['4.Ng5 tấn công f7 (sắc bén) hoặc 4.d3 chơi an toàn', 'Nhập thành sớm, đừng để Tượng c4 bị đổi mất tempo'],
    black: ['Sau 4.Ng5 đi 4...d5 và nhớ 5...Na5', 'Chấp nhận thí tốt để đổi lấy tốc độ phát triển'],
    tip: 'Điểm f7 chỉ được Vua bảo vệ. Luôn đếm số quân tấn công và bảo vệ f7.' },
  { re: /Evans Gambit/, vn: 'Gambit Evans',
    idea: 'Trắng thí tốt b4 để kéo Tượng c5 đi, đổi lại được đi c3 và d4 với tempo, trung tâm lớn và tấn công nhanh.',
    white: ['c3, d4 mở trung tâm, Qb3 nhắm f7', 'Tượng c1 lên a3 ngăn Đen nhập thành'],
    black: ['Nhận tốt rồi lui Tượng về a5 hoặc e7', 'Trả lại tốt khi cần để phát triển và nhập thành'],
    tip: 'Gambit cổ điển, rất hay để học tấn công.' },
  { re: /Giuoco Pian/, vn: 'Giuoco Piano (Ván êm)',
    idea: 'Cả hai Tượng đứng c4 và c5 nhắm vào f7 và f2. Trắng chuẩn bị c3 và d4 để chiếm trung tâm, hoặc d3 để xây dựng chậm.',
    white: ['c3 rồi d4 chiếm trung tâm', 'Nhập thành, Re1, Nbd2-f1-g3 kiểu hiện đại'],
    black: ['...Nf6, ...d6, nhập thành', 'Giữ Tượng c5 hoạt động; lui về b6 khi bị d4 đuổi'],
    tip: 'Khai cuộc tốt nhất để người mới học nguyên tắc: phát triển, trung tâm, nhập thành.' },
  { re: /Italian Game/, vn: 'Khai cuộc Ý',
    idea: 'Sau 1.e4 e5 2.Nf3 Nc6 3.Bc4, Tượng Trắng nhắm thẳng vào f7, điểm yếu nhất của Đen lúc đầu ván.',
    white: ['Nhập thành nhanh, sau đó c3 và d4', 'Hoặc d3 chắc chắn rồi tấn công cánh Vua'],
    black: ['3...Bc5 (Giuoco Piano) hoặc 3...Nf6 (Hai Mã)', 'Không để f7 bị khai thác, nhập thành sớm'],
    tip: 'Tránh 3...d6?! quá thụ động, và cẩn thận với Ng5 khi f7 yếu.' },
  { re: /Ruy Lopez: Berlin/, vn: 'Phòng thủ Berlin',
    idea: 'Đen đi 3...Nf6 phản công e4. Biến chính thường đổi Hậu sớm và vào tàn cuộc Berlin nổi tiếng là rất khó phá.',
    white: ['O-O rồi Re1 hoặc d3 chơi chậm', 'Trong tàn cuộc, dùng thế tốt đa số cánh Vua'],
    black: ['Chấp nhận mất quyền nhập thành để đổi lấy cặp Tượng', 'Phòng thủ bền, chờ Trắng quá tay'],
    tip: 'Nổi tiếng vì Kramnik dùng để hạ Kasparov năm 2000.' },
  { re: /Ruy Lopez/, vn: 'Khai cuộc Tây Ban Nha (Ruy Lopez)',
    idea: '3.Bb5 tấn công Mã c6, quân đang bảo vệ tốt e5. Trắng chưa ăn được tốt ngay mà tạo áp lực lâu dài lên trung tâm Đen.',
    white: ['Nhập thành, Re1, c3 rồi d4', 'Lui Tượng về a4, b3 và giữ đường chéo nhắm f7'],
    black: ['3...a6 đuổi Tượng (Phòng thủ Morphy), rồi ...Nf6, ...Be7, ...b5', 'Giữ e5 thật vững, nhập thành'],
    tip: 'Sau 3...a6 4.Bxc6 dxc6, 5.Nxe5? bị 5...Qd4! lấy lại tốt.' },
  { re: /Najdorf/, vn: 'Biến Najdorf',
    idea: '5...a6 là nước linh hoạt: ngăn Bb5 và Nb5, chuẩn bị ...e5 hoặc ...e6 và ...b5. Đây là biến sắc bén bậc nhất.',
    white: ['6.Be3, 6.Bg5 hoặc 6.Be2 tùy phong cách', 'Tấn công cánh Vua, thường với f3, g4'],
    black: ['Phản công cánh Hậu bằng ...b5, ...Bb7, cột c', 'Chiếm ô d5 hoặc phá bằng ...d5 đúng lúc'],
    tip: 'Lý thuyết rất dài, học ý tưởng trước khi học thuộc nước đi.' },
  { re: /Dragon/, vn: 'Biến Rồng (Dragon)',
    idea: 'Đen đưa Tượng lên g7 nhắm theo đường chéo dài. Trắng thường nhập thành cánh Hậu và đẩy tốt h4-h5 tấn công Vua Đen.',
    white: ['Be3, Qd2, f3, O-O-O rồi h4-h5', 'Đổi Tượng g7 bằng Bh6'],
    black: ['Phản công cột c, thường thí Xe ở c3', 'Giữ Tượng g7 càng lâu càng tốt'],
    tip: 'Hai bên tấn công ở hai cánh: ai nhanh hơn thường thắng.' },
  { re: /Smith-Morra Gambit(?! Declined)/, vn: 'Gambit Smith-Morra',
    idea: 'Trắng thí tốt d4 rồi c3 để phát triển nhanh và mở cột c, cột d cho Xe.',
    white: ['Nxc3, Nf3, Bc4, O-O, Qe2, Rd1', 'Nhắm vào f7 và ô d6 yếu'],
    black: ['Nhận tốt nhưng phát triển thật cẩn thận', 'Tránh để Hậu đứng trên cột c hoặc d bị Xe đè'],
    tip: 'Bẫy Siberia là một cái bẫy nổi tiếng trong biến này.' },
  { re: /Sicilian Defense: Alapin/, vn: 'Sicilia, biến Alapin (2.c3)',
    idea: 'Trắng chuẩn bị d4 để có cặp tốt trung tâm d4 và e4. Đen thường đáp 2...Nf6 hoặc 2...d5 để đánh trung tâm ngay.',
    white: ['d4, lấy lại bằng tốt c3 nếu được', 'Tránh lý thuyết Sicilia mở rất dài'],
    black: ['2...d5 hoặc 2...Nf6 tấn công e4', 'Phát triển nhanh, không để Trắng có trung tâm miễn phí'],
    tip: 'Lựa chọn tốt cho người không muốn học Sicilia mở.' },
  { re: /^Sicilian Defense/, vn: 'Phòng thủ Sicilia',
    idea: '1...c5 kiểm soát d4 từ cánh. Đen sẵn sàng đổi tốt c lấy tốt d trung tâm để có thế cờ lệch và phản công.',
    white: ['Nf3 rồi d4 mở thế cờ (Sicilia mở)', 'Phát triển nhanh và tấn công cánh Vua'],
    black: ['Phản công cánh Hậu qua cột c nửa mở', 'Chọn cấu trúc ...d6, ...e6 hoặc ...g6'],
    tip: 'Phòng thủ phổ biến nhất trước 1.e4, dẫn tới những ván rất sắc bén.' },
  { re: /French Defense/, vn: 'Phòng thủ Pháp',
    idea: '1...e6 rồi 2...d5: Đen có thế chắc chắn nhưng Tượng c8 bị chính tốt e6 chặn.',
    white: ['Giữ trung tâm, thường đẩy e5 để chiếm không gian', 'Tấn công cánh Vua nơi Đen thiếu quân phòng thủ'],
    black: ['Phá trung tâm Trắng bằng ...c5 và ...f6', 'Tìm cách kích hoạt Tượng c8 (…b6 và …Ba6, hoặc đổi nó đi)'],
    tip: 'Trong biến Tiến (3.e5), mũi nhọn của Đen luôn là ...c5.' },
  { re: /Caro-Kann/, vn: 'Phòng thủ Caro-Kann',
    idea: '1...c6 rồi 2...d5. Giống Pháp nhưng Tượng c8 kịp ra ngoài (…Bf5 hoặc …Bg4) trước khi Đen đi …e6.',
    white: ['Biến Tiến 3.e5 chiếm không gian', 'Hoặc 3.Nc3 cổ điển, đuổi Tượng f5 bằng h4-h5'],
    black: ['Cấu trúc tốt vững, ít điểm yếu', 'Đổi quân và đi vào tàn cuộc tốt'],
    tip: 'Lựa chọn rất tốt cho người thích chơi chắc chắn.' },
  { re: /Scandinavian/, vn: 'Phòng thủ Scandinavia',
    idea: '1...d5 đánh thẳng vào e4. Sau 2.exd5 Qxd5 3.Nc3, Hậu Đen phải lui và Trắng được thêm một nhịp phát triển.',
    white: ['Nc3 đuổi Hậu, d4, Nf3, phát triển nhanh', 'Tận dụng việc Hậu Đen ra sớm để lấy tempo'],
    black: ['Hậu về a5 hoặc d6, rồi ...Nf6, ...Bf5 hoặc ...Bg4, ...c6', 'Chơi đơn giản, cấu trúc gọn'],
    tip: 'Dễ học vì Trắng khó tránh vào thế cờ này.' },
  { re: /Alekhine/, vn: 'Phòng thủ Alekhine',
    idea: '1...Nf6 dụ các tốt Trắng tiến lên (e5, c4, d4, f4), rồi Đen tấn công trung tâm đã bị kéo quá dài.',
    white: ['Chiếm không gian nhưng đừng đẩy tốt quá xa', 'Phát triển quân trước khi tấn công'],
    black: ['Lui Mã về b6, phá trung tâm bằng ...d6, ...c5', 'Kiên nhẫn chờ trung tâm Trắng lộ điểm yếu'],
    tip: 'Khai cuộc khiêu khích, cần hiểu rõ khi nào phản công.' },
  { re: /Pirc/, vn: 'Phòng thủ Pirc',
    idea: 'Đen đi ...d6, ...Nf6, ...g6, ...Bg7: để Trắng chiếm trung tâm rồi phản công sau.',
    white: ['Tấn công Áo (f4) hoặc Be3, Qd2 và nhập thành xa', 'Tận dụng không gian lớn'],
    black: ['Nhập thành, phá trung tâm bằng ...e5 hoặc ...c5', 'Dùng Tượng g7 trên đường chéo dài'],
    tip: 'Linh hoạt nhưng nhường Trắng nhiều không gian.' },
  { re: /^Modern Defense/, vn: 'Phòng thủ Hiện đại',
    idea: 'Đen đi ...g6 và ...Bg7 trước, giữ thế linh hoạt, trì hoãn ...Nf6 để tùy biến.',
    white: ['Lập trung tâm e4, d4 và phát triển tự nhiên', 'Không vội tấn công khi chưa phát triển xong'],
    black: ['Phản công trung tâm bằng ...c5, ...d6, ...e5', 'Giữ Tượng g7 mạnh'],
    tip: 'Gần với Pirc, nhiều cách chuyển đổi qua lại.' },
  { re: /Stafford/, vn: 'Gambit Stafford',
    idea: 'Sau 3.Nxe5 Nc6!?, Đen thí tốt để phát triển nhanh và đặt nhiều bẫy chiếu hết quanh Vua Trắng.',
    white: ['4.Nxc6 dxc6 rồi d3 hoặc Nc3 là an toàn', 'Không tham ăn, không để Tượng c5 và Mã đè vào f2'],
    black: ['Phát triển thật nhanh: ...Bc5, ...Ng4, ...Qh4', 'Nhắm vào f2 và ô h2'],
    tip: 'Trắng chơi đúng thì Đen chỉ bị thiếu một tốt. Hay để biết, không nên phụ thuộc.' },
  { re: /Petrov/, vn: 'Phòng thủ Petrov (Ván Nga)',
    idea: 'Thay vì bảo vệ e5, Đen phản công tốt e4 bằng 2...Nf6. Thế cờ đối xứng, rất chắc chắn.',
    white: ['3.Nxe5 rồi Nf3, hoặc 3.d4 mở trung tâm', 'Phát triển nhanh để tận dụng lượt đi trước'],
    black: ['Sau 3.Nxe5 phải đi 3...d6 trước rồi mới ...Nxe4', 'Phát triển đối xứng, nhập thành'],
    tip: 'Bẫy kinh điển: 3.Nxe5 Nxe4? 4.Qe2! Nf6?? 5.Nc6+ mở đường chiếu, ăn Hậu Đen.' },
  { re: /Philidor/, vn: 'Phòng thủ Philidor',
    idea: '2...d6 bảo vệ e5 bằng tốt. Chắc chắn nhưng thụ động, vì Tượng f8 bị chính tốt d6 chặn.',
    white: ['d4 gây áp lực e5, phát triển tự nhiên', 'Chiếm không gian và dùng lợi thế phát triển'],
    black: ['...Nf6, ...Be7, ...O-O, giữ e5', 'Hoặc đổi ...exd4 để mở thế cờ'],
    tip: 'Có một cái bẫy nổi tiếng: chiếu hết Légal thường xuất hiện ở khai cuộc kiểu này.' },
  { re: /Scotch/, vn: 'Ván Scotland (Scotch)',
    idea: '3.d4 mở trung tâm ngay lập tức. Sau 3...exd4 4.Nxd4 Trắng có không gian và thế cờ thoáng.',
    white: ['Mã d4 mạnh, phát triển nhanh, nhập thành', 'Chuẩn bị e5 hoặc f4 để tấn công'],
    black: ['4...Bc5 hoặc 4...Nf6 tấn công ngay', 'Đổi Mã ở d4 khi có lợi'],
    tip: 'Đơn giản và mở, hợp với người thích quân hoạt động.' },
  { re: /Four Knights|Three Knights/, vn: 'Ván Bốn Mã',
    idea: 'Cả hai bên đưa Mã về ô tự nhiên nhất. Thế cờ cân bằng, dễ chơi, hợp để luyện nguyên tắc phát triển.',
    white: ['Bb5 (Tây Ban Nha) hoặc d4 (Scotch)', 'Nhập thành và mở trung tâm'],
    black: ['Phát triển đối xứng, nhập thành', 'Cẩn thận khi đối xứng quá lâu'],
    tip: 'Tốt cho người mới vì ít bẫy lý thuyết.' },
  { re: /^Vienna Game|^Vienna Gambit/, vn: 'Ván Vienna',
    idea: '2.Nc3 phát triển Mã và chuẩn bị f4 để tấn công, hoặc Bc4 nhắm f7.',
    white: ['f4 mở cột f (Gambit Vienna)', 'Hoặc g3 và Bg2 chơi vị trí'],
    black: ['...Nf6 và phản công ...d5 đúng lúc', 'Không để bị cuốn vào tấn công quá sớm'],
    tip: 'Gambit Vienna có nhiều cú đánh nhanh, rất hợp ván chớp.' },
  { re: /King's Gambit/, vn: 'Gambit Vua',
    idea: '2.f4 thí tốt f để kéo tốt e5 khỏi trung tâm và mở cột f cho Xe tấn công f7.',
    white: ['Nf3, Bc4, d4, nhập thành nhanh', 'Dùng cột f mở và trung tâm để tấn công'],
    black: ['Nhận tốt rồi trả lại đúng lúc, hoặc từ chối bằng ...Bc5', 'Phản công trung tâm bằng ...d5'],
    tip: 'Khai cuộc lãng mạn của thế kỷ 19, đầy tấn công.' },
  { re: /Bishop's Opening/, vn: 'Khai cuộc Tượng',
    idea: '2.Bc4 đưa Tượng nhắm f7 ngay, giữ linh hoạt để chuyển sang Ý hoặc Vienna.',
    white: ['d3, Nf3, Nc3, nhập thành', 'Có thể chơi f4 như Gambit Vua'],
    black: ['2...Nf6 phản công e4', 'Phát triển nhanh và giữ f7'],
    tip: 'Đơn giản, ít lý thuyết.' },
  { re: /Center Game|Danish/, vn: 'Ván Trung tâm / Gambit Đan Mạch',
    idea: '2.d4 mở trung tâm ngay. Nếu Hậu ăn lại ở d4 thì Đen đuổi bằng ...Nc6 và được tempo. Gambit Đan Mạch thí tốt để phát triển siêu tốc.',
    white: ['Lấy lại tốt, phát triển nhanh', 'Trong Gambit Đan Mạch, hai Tượng nhắm vào Vua Đen'],
    black: ['...Nc6 đuổi Hậu, ...Nf6, nhập thành', 'Trả lại tốt để phát triển khi cần'],
    tip: 'Nhắc nhở: đưa Hậu ra quá sớm thường bị mất nhịp.' },
  { re: /Ponziani/, vn: 'Khai cuộc Ponziani',
    idea: '3.c3 chuẩn bị d4 để có trung tâm tốt, nhưng lấy mất ô c3 của Mã.',
    white: ['d4 chiếm trung tâm', 'Qa4 ghim Mã c6 trong một số biến'],
    black: ['Phản công ngay bằng ...Nf6 hoặc ...d5', 'Tận dụng việc Trắng phát triển chậm'],
    tip: 'Ít gặp, bất ngờ với đối thủ.' },
  { re: /Elephant/, vn: 'Gambit Voi (Elephant)',
    idea: 'Một gambit mạo hiểm: thí tốt để tạo biến động, nhưng nếu đối phương chơi đúng thì bên thí thường yếu thế.',
    white: ['Phát triển tự nhiên, không tham ăn thêm', 'Nhập thành sớm, giữ Vua an toàn'],
    black: ['Bên thí tốt cần tấn công ngay', 'Học các bẫy chính để không bị thua nhanh'],
    tip: 'Gặp những khai cuộc này, cứ chơi theo nguyên tắc là đủ.' },
  { re: /Latvian/, vn: 'Gambit Latvia',
    idea: 'Một gambit mạo hiểm: thí tốt để tạo biến động, nhưng nếu đối phương chơi đúng thì bên thí thường yếu thế.',
    white: ['Phát triển tự nhiên, không tham ăn thêm', 'Nhập thành sớm, giữ Vua an toàn'],
    black: ['Bên thí tốt cần tấn công ngay', 'Học các bẫy chính để không bị thua nhanh'],
    tip: 'Gặp những khai cuộc này, cứ chơi theo nguyên tắc là đủ.' },
  { re: /Englund/, vn: 'Gambit Englund',
    idea: 'Một gambit mạo hiểm: thí tốt để tạo biến động, nhưng nếu đối phương chơi đúng thì bên thí thường yếu thế.',
    white: ['Phát triển tự nhiên, không tham ăn thêm', 'Nhập thành sớm, giữ Vua an toàn'],
    black: ['Bên thí tốt cần tấn công ngay', 'Học các bẫy chính để không bị thua nhanh'],
    tip: 'Gặp những khai cuộc này, cứ chơi theo nguyên tắc là đủ.' },
  { re: /King's Knight Opening/, vn: 'Khai cuộc Mã Vua',
    idea: '2.Nf3 phát triển Mã và tấn công ngay tốt e5. Đen thường bảo vệ bằng 2...Nc6, hoặc 2...d6 (Philidor), hoặc phản công 2...Nf6 (Petrov).',
    white: ['Tiếp theo Bb5 (Tây Ban Nha), Bc4 (Ý) hoặc d4 (Scotch)', 'Phát triển Mã trước Tượng'],
    black: ['2...Nc6 là nước tự nhiên nhất', 'Đừng bảo vệ bằng 2...f6? (Phòng thủ Damiano) hay 2...Qf6'],
    tip: 'Sau 2...f6? Trắng có ngay 3.Nxe5! rất mạnh.' },
  { re: /King's Pawn Game/, vn: 'Ván Tốt Vua',
    idea: '1.e4 chiếm trung tâm và mở đường cho Hậu và Tượng f1. Đây là nước đi phổ biến nhất ở mọi trình độ.',
    white: ['Nf3, Bc4 hoặc Bb5, nhập thành', 'Phát triển Mã trước Tượng, không đi Hậu sớm'],
    black: ['1...e5 cân bằng, hoặc 1...c5, 1...e6, 1...c6', 'Giành phần trung tâm của mình'],
    tip: 'Nguyên tắc vàng: trung tâm, phát triển, nhập thành.' },
  { re: /London System/, vn: 'Hệ thống London',
    idea: 'Trắng đi d4, Bf4, e3, Nf3, c3, Bd3, Nbd2 gần như bất kể Đen làm gì. Hệ thống chắc chắn và dễ học.',
    white: ['Dựng đủ hệ thống rồi mới tấn công', 'Mã e5 kết hợp f4 hoặc Qf3 cho tấn công cánh Vua'],
    black: ['...c5 và ...Qb6 đánh vào b2', 'Hoặc ...Nh5 đổi Tượng f4'],
    tip: 'Rất hợp để lên trình: ít lý thuyết, kế hoạch rõ ràng.' },
  { re: /Queen's Gambit Accepted/, vn: 'Gambit Hậu chấp nhận',
    idea: 'Đen nhận tốt 2...dxc4 nhưng không cố giữ. Đen dùng thời gian đó để phát triển và đánh ...c5 hoặc ...e5.',
    white: ['e3 hoặc e4, rồi Bxc4 lấy lại tốt', 'Chiếm trung tâm bằng tốt'],
    black: ['...Nf6, ...e6, ...c5 và phát triển nhanh', 'Đừng cố giữ tốt c4 bằng ...b5'],
    tip: 'Giữ tốt thừa bằng ...b5 thường bị a4 phá và mất nhiều hơn.' },
  { re: /Queen's Gambit Declined/, vn: 'Gambit Hậu từ chối',
    idea: '2...e6 giữ tốt d5 vững chắc. Vấn đề lớn nhất của Đen là Tượng c8 bị kẹt sau tốt e6.',
    white: ['Nc3, Bg5 gây áp lực d5', 'Đổi cxd5 rồi tấn công thiểu số b4-b5'],
    black: ['...Nf6, ...Be7, ...O-O, chờ giải phóng bằng ...c5 hoặc ...e5', 'Đổi quân để giảm áp lực'],
    tip: 'Bẫy Voi (Elephant Trap): sau ...Nbd7, nếu Trắng tham ăn tốt d5 bằng Mã thì bị mất quân.' },
  { re: /Semi-Slav/, vn: 'Phòng thủ Bán Slav',
    idea: 'Đen kết hợp ...c6 và ...e6: trung tâm cực vững, sẵn sàng ăn tốt c4 rồi phản công ...b5 (biến Meran).',
    white: ['e3 và Bd3, hoặc Bg5 sắc bén', 'Chiếm e4 khi có thể'],
    black: ['...dxc4 và ...b5, ...Bb7, ...c5', 'Giữ thế cờ đàn hồi'],
    tip: 'Một trong những phòng thủ phức tạp nhất trước 1.d4.' },
  { re: /^Slav Defense/, vn: 'Phòng thủ Slav',
    idea: '2...c6 bảo vệ d5 mà vẫn để Tượng c8 ra được ô f5 hoặc g4 trước khi đi ...e6.',
    white: ['Nc3, Nf3, e3 hoặc a4 ngăn ...b5', 'Lấy lại tốt c4 nếu Đen ăn'],
    black: ['...Bf5 sớm, rồi ...e6', 'Cấu trúc tốt vững chắc'],
    tip: 'Giải quyết tốt vấn đề Tượng c8 của Gambit Hậu từ chối.' },
  { re: /^Catalan Opening/, vn: 'Khai cuộc Catalan',
    idea: 'Trắng kết hợp d4, c4 với g3 và Bg2: Tượng g2 đè đường chéo dài, tạo áp lực lâu dài lên cánh Hậu Đen.',
    white: ['Qc2 hoặc Qa4 lấy lại tốt c4', 'Áp lực bền bỉ trên đường chéo h1-a8'],
    black: ['...dxc4 rồi ...b5 hoặc ...c5', 'Hóa giải Tượng g2 bằng ...c6 hoặc đổi quân'],
    tip: 'Khai cuộc vị trí, hợp người kiên nhẫn.' },
  { re: /Queen's Gambit/, vn: 'Gambit Hậu',
    idea: '2.c4 thí tốt c để kéo tốt d5 khỏi trung tâm. Thật ra không phải thí thật, vì Trắng thường lấy lại tốt dễ dàng.',
    white: ['Nc3, Nf3, Bg5 hoặc Bf4', 'Chiếm trung tâm bằng e4 khi có thể'],
    black: ['Từ chối bằng 2...e6 hoặc 2...c6, hoặc nhận bằng 2...dxc4', 'Giữ trung tâm d5'],
    tip: 'Một trong những khai cuộc lâu đời và vững chắc nhất.' },
  { re: /Nimzo-Indian/, vn: 'Phòng thủ Nimzo-Ấn',
    idea: '3...Bb4 ghim Mã c3, sẵn sàng đổi Tượng lấy Mã để làm hỏng cấu trúc tốt Trắng và kiểm soát ô e4.',
    white: ['Qc2 hoặc a3 để có cặp Tượng', 'e3 và Bd3 phát triển chắc'],
    black: ['Đổi Bxc3 khi tốt Trắng bị chồng', 'Kiểm soát e4 bằng ...b6, ...Bb7 hoặc ...d5'],
    tip: 'Rất được các kiện tướng ưa chuộng.' },
  { re: /Bogo-Indian/, vn: 'Phòng thủ Bogo-Ấn',
    idea: '3...Bb4+ chiếu để đơn giản hóa phát triển, thường đổi Tượng lấy Tượng hoặc Mã.',
    white: ['Bd2 hoặc Nbd2 chặn chiếu', 'Giữ trung tâm, g3 và Bg2'],
    black: ['...Qe7 bảo vệ, ...O-O, ...d6', 'Chơi chắc, ít điểm yếu'],
    tip: 'Lựa chọn yên tĩnh trước 1.d4.' },
  { re: /Queen's Indian/, vn: 'Phòng thủ Ấn Độ Hậu',
    idea: '...b6 và ...Bb7 kiểm soát ô e4 từ xa. Thế cờ chắc chắn, ít rủi ro.',
    white: ['g3 và Bg2 đối đầu Tượng b7', 'a3 để ngăn ...Bb4'],
    black: ['...Bb7, ...Be7, ...O-O', 'Giữ e4 dưới tầm kiểm soát'],
    tip: 'Phòng thủ vững cho người thích chơi vị trí.' },
  { re: /King's Indian Attack/, vn: 'Tấn công Ấn Độ Vua',
    idea: 'Trắng dựng hệ thống Nf3, g3, Bg2, O-O, d3, e4: giống Phòng thủ Ấn Độ Vua nhưng đảo màu và hơn một nước.',
    white: ['e5 chiếm không gian, tấn công cánh Vua', 'Nbd2, Re1, h4 là các nước quen thuộc'],
    black: ['Chiếm trung tâm, phản công cánh Hậu', 'Không để Trắng tấn công cánh Vua dễ dàng'],
    tip: 'Một hệ thống dùng được trước gần như mọi phòng thủ.' },
  { re: /King's Indian/, vn: 'Phòng thủ Ấn Độ Vua',
    idea: 'Đen để Trắng lập trung tâm tốt lớn, nhập thành nhanh, rồi phản công bằng ...e5 hoặc ...c5 và thường tấn công cánh Vua bằng ...f5.',
    white: ['Chiếm không gian, tấn công cánh Hậu bằng c5', 'Giữ trung tâm vững'],
    black: ['...e5, ...Nc6 hoặc ...Na6, rồi ...f5', 'Tượng g7 là quân quan trọng nhất'],
    tip: 'Khai cuộc chiến đấu yêu thích của Fischer và Kasparov.' },
  { re: /Grünfeld/, vn: 'Phòng thủ Grünfeld',
    idea: 'Đen đi ...g6 và ...d5: cho Trắng lập trung tâm lớn rồi tấn công nó bằng Tượng g7, ...c5 và ...Nc6.',
    white: ['cxd5, e4 lập trung tâm lớn', 'Giữ trung tâm và tấn công cánh Vua'],
    black: ['Áp lực liên tục lên d4', '...c5, ...Nc6, ...Qa5 là các vũ khí chính'],
    tip: 'Sắc bén và giàu lý thuyết.' },
  { re: /Benko/, vn: 'Gambit Benko',
    idea: 'Đen thí tốt b5 để mở cột a và b cho Xe, tạo áp lực lâu dài cánh Hậu.',
    white: ['Nhận tốt và giữ chắc', 'Tìm cách chơi e4-e5 ở trung tâm'],
    black: ['Xe trên cột a, b; Tượng g7 đè đường chéo', 'Không vội lấy lại tốt'],
    tip: 'Thí tốt vì hoạt động, rất hợp để học chơi vị trí.' },
  { re: /Benoni/, vn: 'Phòng thủ Benoni',
    idea: '...c5 thách thức d4, tạo cấu trúc tốt lệch: Trắng nhiều quân ở trung tâm, Đen chơi cánh Hậu với ...a6, ...b5.',
    white: ['e4-e5 phá trung tâm', 'Kiểm soát ô c4 và b5'],
    black: ['Tượng g7, ...Re8, ...a6, ...b5', 'Chơi năng động, chấp nhận rủi ro'],
    tip: 'Sắc bén, cần tính toán chính xác.' },
  { re: /^Dutch Defense/, vn: 'Phòng thủ Hà Lan',
    idea: '1...f5 kiểm soát e4 và hướng tới tấn công cánh Vua, nhưng làm yếu Vua Đen trên đường chéo e8-h5.',
    white: ['g3 và Bg2, chiếm e4 khi có thể', 'Tấn công đường chéo yếu e8-h5'],
    black: ['Stonewall (...d5, ...e6, ...c6) hoặc Leningrad (...g6)', 'Tấn công cánh Vua bằng ...Qe8-h5'],
    tip: 'Cẩn thận các đòn chiếu sớm bằng Qh5.' },
  { re: /Tarrasch/, vn: 'Phòng thủ Tarrasch',
    idea: 'Đen đi ...c5 sớm, chấp nhận tốt d cô lập để đổi lấy quân hoạt động và không gian.',
    white: ['Phong tỏa tốt d5 cô lập', 'Đổi quân để tốt cô lập thành điểm yếu'],
    black: ['Dùng tốt d5 để quân hoạt động', 'Tấn công trước khi vào tàn cuộc'],
    tip: 'Bài học kinh điển về tốt cô lập.' },
  { re: /Budapest/, vn: 'Gambit Budapest',
    idea: '2...e5!? thí tốt để quân Đen hoạt động nhanh, thường lấy lại tốt e5 sau đó.',
    white: ['Giữ tốt e5 bằng Bf4, Nf3', 'Không tham giữ tốt bằng mọi giá'],
    black: ['...Ng4, ...Nc6, ...Bb4+ lấy lại tốt', 'Chơi nhanh, nhiều bẫy'],
    tip: 'Bẫy Kieninger là cái bẫy nổi tiếng trong gambit này.' },
  { re: /Indian Defense/, vn: 'Phòng thủ Ấn Độ',
    idea: '1...Nf6 linh hoạt: kiểm soát e4, chưa lộ cấu trúc tốt, có thể chuyển sang nhiều phòng thủ khác nhau.',
    white: ['2.c4 chiếm không gian, hoặc hệ thống London/Colle', 'Phát triển tự nhiên'],
    black: ['Chọn ...e6 (Nimzo, Ấn Độ Hậu) hoặc ...g6 (Ấn Độ Vua, Grünfeld)', 'Giữ linh hoạt'],
    tip: 'Nước đáp phổ biến nhất trước 1.d4.' },
  { re: /^English Opening/, vn: 'Khai cuộc Anh',
    idea: '1.c4 kiểm soát d5 từ cánh, thường giống Phòng thủ Sicilia nhưng đảo màu và hơn một nước.',
    white: ['Nc3, g3, Bg2 kiểm soát đường chéo trắng', 'Chơi vị trí, chuyển sang d4 khi thuận lợi'],
    black: ['1...e5 (Sicilia đảo màu) hoặc 1...c5 đối xứng', 'Chiếm trung tâm bằng tốt'],
    tip: 'Linh hoạt, nhiều cách chuyển sang khai cuộc 1.d4.' },
  { re: /Réti|Zukertort/, vn: 'Khai cuộc Réti / Zukertort (1.Nf3)',
    idea: '1.Nf3 phát triển Mã trước, giữ nhiều lựa chọn: d4, c4 hoặc g3. Trắng chờ xem Đen dựng thế cờ gì.',
    white: ['c4 và g3 (Réti), hoặc d4 chuyển sang 1.d4', 'Kiểm soát trung tâm từ xa'],
    black: ['...d5 và ...Nf6 chiếm trung tâm', 'Chơi chắc chắn, phát triển tự nhiên'],
    tip: 'Nước khai cuộc linh hoạt, ít bị bất ngờ.' },
  { re: /Bird/, vn: 'Khai cuộc Bird',
    idea: '1.f4 kiểm soát e5, giống Phòng thủ Hà Lan đảo màu. Nhưng làm yếu Vua Trắng trên đường chéo e1-h4.',
    white: ['Nf3, e3, b3 và Bb2 (Tượng đè e5)', 'Cẩn thận đường chéo e1-h4'],
    black: ['1...d5 chắc chắn, hoặc Gambit From 1...e5', 'Tấn công Vua Trắng yếu'],
    tip: 'Gambit From (1...e5) là phản đòn sắc bén.' },
  { re: /Queen's Pawn Game|Colle|Torre|Trompowsky|Richter-Veresov|Jobava/, vn: 'Ván Tốt Hậu',
    idea: '1.d4 chiếm trung tâm. Ván cờ thường khép kín hơn 1.e4, chơi theo kế hoạch và cấu trúc tốt nhiều hơn là đòn chiến thuật sớm.',
    white: ['Nf3, c4 hoặc một hệ thống như London, Colle', 'Phát triển ổn định, kiểm soát e5'],
    black: ['1...d5 hoặc 1...Nf6 giành trung tâm', 'Không để Trắng chiếm e4 miễn phí'],
    tip: 'Hợp với người thích kế hoạch dài hơi.' },
];

const FALLBACK = {
  vn: 'Khai cuộc ít gặp',
  idea: 'Đây là một khai cuộc ít phổ biến. Hãy dựa vào nguyên tắc chung: chiếm trung tâm, phát triển quân nhẹ, nhập thành sớm.',
  white: ['Phát triển Mã và Tượng về phía trung tâm', 'Nhập thành trong khoảng 10 nước đầu'],
  black: ['Giành phần trung tâm bằng tốt', 'Không đi một quân hai lần khi chưa cần'],
  tip: 'Khai cuộc lạ không nguy hiểm nếu bạn chơi đúng nguyên tắc.',
};

export function guideFor(name) {
  if (!name) return null;
  const g = GUIDES.find((x) => x.re.test(name));
  return g || FALLBACK;
}

export function vnName(name) {
  const g = guideFor(name);
  if (g && g !== FALLBACK) return g.vn;
  const fam = name.split(':')[0].split(',')[0].trim();
  const rules = [
    [/^(.*) Gambit Accepted$/, 'Gambit $1 chấp nhận'], [/^(.*) Gambit Declined$/, 'Gambit $1 từ chối'],
    [/^(.*) Countergambit$/, 'Phản gambit $1'], [/^(.*) Gambit$/, 'Gambit $1'], [/^(.*) Defense$/, 'Phòng thủ $1'],
    [/^(.*) Opening$/, 'Khai cuộc $1'], [/^(.*) Game$/, 'Ván $1'], [/^(.*) Attack$/, 'Tấn công $1'], [/^(.*) System$/, 'Hệ thống $1'],
  ];
  for (const [re, out] of rules) if (re.test(fam)) return fam.replace(re, out);
  return fam;
}
